var searchData=
[
  ['data_5fchunk_5freader_0',['data_chunk_reader',['../classcudf_1_1io_1_1text_1_1data__chunk__reader.html',1,'cudf::io::text']]],
  ['data_5fchunk_5fsource_1',['data_chunk_source',['../classcudf_1_1io_1_1text_1_1data__chunk__source.html',1,'cudf::io::text']]],
  ['data_5fsink_2',['data_sink',['../classcudf_1_1io_1_1data__sink.html',1,'cudf::io']]],
  ['data_5ftype_3',['data_type',['../classcudf_1_1data__type.html',1,'cudf']]],
  ['datasource_4',['datasource',['../classcudf_1_1io_1_1datasource.html',1,'cudf::io']]],
  ['decimal_5fstatistics_5',['decimal_statistics',['../structcudf_1_1io_1_1decimal__statistics.html',1,'cudf::io']]],
  ['default_5fallocator_6',['default_allocator',['../classdefault__allocator.html',1,'']]],
  ['device_5fdata_5fchunk_7',['device_data_chunk',['../classcudf_1_1io_1_1text_1_1device__data__chunk.html',1,'cudf::io::text']]],
  ['device_5fdata_5freference_8',['device_data_reference',['../structcudf_1_1ast_1_1detail_1_1device__data__reference.html',1,'cudf::ast::detail']]],
  ['device_5fspan_9',['device_span',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fspan_3c_20ast_5foperator_20const_20_3e_10',['device_span&lt; ast_operator const &gt;',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fspan_3c_20cudf_3a_3aast_3a_3adetail_3a_3adevice_5fdata_5freference_20const_20_3e_11',['device_span&lt; cudf::ast::detail::device_data_reference const &gt;',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fspan_3c_20cudf_3a_3adetail_3a_3afixed_5fwidth_5fscalar_5fdevice_5fview_5fbase_20const_20_3e_12',['device_span&lt; cudf::detail::fixed_width_scalar_device_view_base const &gt;',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fspan_3c_20cudf_3a_3aio_3a_3atext_3a_3adetail_3a_3atrie_5fnode_20const_20_3e_13',['device_span&lt; cudf::io::text::detail::trie_node const &gt;',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['device_5fspan_3c_20cudf_3a_3asize_5ftype_20const_20_3e_14',['device_span&lt; cudf::size_type const &gt;',['../structcudf_1_1device__span.html',1,'cudf']]],
  ['dictionary_5fcolumn_5fview_15',['dictionary_column_view',['../classcudf_1_1dictionary__column__view.html',1,'cudf']]],
  ['dictionary_5fwrapper_16',['dictionary_wrapper',['../structcudf_1_1dictionary__wrapper.html',1,'cudf']]],
  ['dispatch_5faggregation_17',['dispatch_aggregation',['../structcudf_1_1detail_1_1dispatch__aggregation.html',1,'cudf::detail']]],
  ['dispatch_5fsource_18',['dispatch_source',['../structcudf_1_1detail_1_1dispatch__source.html',1,'cudf::detail']]],
  ['dispatch_5fstorage_5ftype_19',['dispatch_storage_type',['../structcudf_1_1dispatch__storage__type.html',1,'cudf']]],
  ['dispatch_5funary_5foperator_5ftypes_20',['dispatch_unary_operator_types',['../structcudf_1_1ast_1_1detail_1_1dispatch__unary__operator__types.html',1,'cudf::ast::detail']]],
  ['domain_21',['domain',['../classnvtx3_1_1domain.html',1,'nvtx3']]],
  ['domain_5fprocess_5frange_22',['domain_process_range',['../classnvtx3_1_1domain__process__range.html',1,'nvtx3']]],
  ['domain_5fthread_5frange_23',['domain_thread_range',['../classnvtx3_1_1domain__thread__range.html',1,'nvtx3']]],
  ['double_5fstatistics_24',['double_statistics',['../structcudf_1_1io_1_1double__statistics.html',1,'cudf::io']]],
  ['dremel_5fdata_25',['dremel_data',['../structcudf_1_1detail_1_1dremel__data.html',1,'cudf::detail']]],
  ['dremel_5fdevice_5fview_26',['dremel_device_view',['../structcudf_1_1detail_1_1dremel__device__view.html',1,'cudf::detail']]],
  ['duration_5fscalar_27',['duration_scalar',['../classcudf_1_1duration__scalar.html',1,'cudf']]],
  ['duration_5fscalar_5fdevice_5fview_28',['duration_scalar_device_view',['../classcudf_1_1duration__scalar__device__view.html',1,'cudf']]]
];
