var searchData=
[
  ['scalar_0',['scalar',['../classcudf_1_1scalar.html',1,'cudf']]],
  ['scaled_5finteger_1',['scaled_integer',['../structnumeric_1_1scaled__integer.html',1,'numeric']]],
  ['scan_5faggregation_2',['scan_aggregation',['../classcudf_1_1scan__aggregation.html',1,'cudf']]],
  ['scan_5frequest_3',['scan_request',['../structcudf_1_1groupby_1_1scan__request.html',1,'cudf::groupby']]],
  ['scan_5ftile_5fstate_4',['scan_tile_state',['../structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state.html',1,'cudf::io::text::detail']]],
  ['scan_5ftile_5fstate_5fcallback_5',['scan_tile_state_callback',['../structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state__callback.html',1,'cudf::io::text::detail']]],
  ['scan_5ftile_5fstate_5fview_6',['scan_tile_state_view',['../structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state__view.html',1,'cudf::io::text::detail']]],
  ['schema_5felement_7',['schema_element',['../structcudf_1_1io_1_1schema__element.html',1,'cudf::io']]],
  ['segmented_5freduce_5faggregation_8',['segmented_reduce_aggregation',['../classcudf_1_1segmented__reduce__aggregation.html',1,'cudf']]],
  ['simple_5faggregations_5fcollector_9',['simple_aggregations_collector',['../classcudf_1_1detail_1_1simple__aggregations__collector.html',1,'cudf::detail']]],
  ['single_5fdispatch_5fbinary_5foperator_5ftypes_10',['single_dispatch_binary_operator_types',['../structcudf_1_1ast_1_1detail_1_1single__dispatch__binary__operator__types.html',1,'cudf::ast::detail']]],
  ['sink_5finfo_11',['sink_info',['../structcudf_1_1io_1_1sink__info.html',1,'cudf::io']]],
  ['sort_5fgroupby_5fhelper_12',['sort_groupby_helper',['../structcudf_1_1groupby_1_1detail_1_1sort_1_1sort__groupby__helper.html',1,'cudf::groupby::detail::sort']]],
  ['source_5finfo_13',['source_info',['../structcudf_1_1io_1_1source__info.html',1,'cudf::io']]],
  ['span_5fbase_14',['span_base',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20ast_5foperator_20const_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20ast_5foperator_20const_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_15',['span_base&lt; ast_operator const, cudf::dynamic_extent, device_span&lt; ast_operator const, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20cudf_3a_3aast_3a_3adetail_3a_3adevice_5fdata_5freference_20const_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20cudf_3a_3aast_3a_3adetail_3a_3adevice_5fdata_5freference_20const_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_16',['span_base&lt; cudf::ast::detail::device_data_reference const, cudf::dynamic_extent, device_span&lt; cudf::ast::detail::device_data_reference const, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20cudf_3a_3adetail_3a_3afixed_5fwidth_5fscalar_5fdevice_5fview_5fbase_20const_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20cudf_3a_3adetail_3a_3afixed_5fwidth_5fscalar_5fdevice_5fview_5fbase_20const_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_17',['span_base&lt; cudf::detail::fixed_width_scalar_device_view_base const, cudf::dynamic_extent, device_span&lt; cudf::detail::fixed_width_scalar_device_view_base const, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20cudf_3a_3aio_3a_3atext_3a_3adetail_3a_3atrie_5fnode_20const_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20cudf_3a_3aio_3a_3atext_3a_3adetail_3a_3atrie_5fnode_20const_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_18',['span_base&lt; cudf::io::text::detail::trie_node const, cudf::dynamic_extent, device_span&lt; cudf::io::text::detail::trie_node const, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20cudf_3a_3asize_5ftype_20const_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20cudf_3a_3asize_5ftype_20const_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_19',['span_base&lt; cudf::size_type const, cudf::dynamic_extent, device_span&lt; cudf::size_type const, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20t_2c_20cudf_3a_3adynamic_5fextent_2c_20device_5fspan_3c_20t_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_20',['span_base&lt; T, cudf::dynamic_extent, device_span&lt; T, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['span_5fbase_3c_20t_2c_20cudf_3a_3adynamic_5fextent_2c_20host_5fspan_3c_20t_2c_20cudf_3a_3adynamic_5fextent_20_3e_20_3e_21',['span_base&lt; T, cudf::dynamic_extent, host_span&lt; T, cudf::dynamic_extent &gt; &gt;',['../classcudf_1_1detail_1_1span__base.html',1,'cudf::detail']]],
  ['special_5fcase_5fmapping_22',['special_case_mapping',['../structcudf_1_1strings_1_1detail_1_1special__case__mapping.html',1,'cudf::strings::detail']]],
  ['std_5faggregation_23',['std_aggregation',['../classcudf_1_1detail_1_1std__aggregation.html',1,'cudf::detail']]],
  ['std_5fvar_5faggregation_24',['std_var_aggregation',['../classcudf_1_1detail_1_1std__var__aggregation.html',1,'cudf::detail']]],
  ['string_5fscalar_25',['string_scalar',['../classcudf_1_1string__scalar.html',1,'cudf']]],
  ['string_5fstatistics_26',['string_statistics',['../structcudf_1_1io_1_1string__statistics.html',1,'cudf::io']]],
  ['string_5fview_27',['string_view',['../classcudf_1_1string__view.html',1,'cudf']]],
  ['strings_5fcolumn_5fview_28',['strings_column_view',['../classcudf_1_1strings__column__view.html',1,'cudf']]],
  ['struct_5fscalar_29',['struct_scalar',['../classcudf_1_1struct__scalar.html',1,'cudf']]],
  ['struct_5fview_30',['struct_view',['../classcudf_1_1struct__view.html',1,'cudf']]],
  ['structs_5fcolumn_5fview_31',['structs_column_view',['../classcudf_1_1structs__column__view.html',1,'cudf']]],
  ['sum_5faggregation_32',['sum_aggregation',['../classcudf_1_1detail_1_1sum__aggregation.html',1,'cudf::detail']]],
  ['sum_5fof_5fsquares_5faggregation_33',['sum_of_squares_aggregation',['../classcudf_1_1detail_1_1sum__of__squares__aggregation.html',1,'cudf::detail']]],
  ['sum_5fstatistics_34',['sum_statistics',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20double_20_3e_35',['sum_statistics&lt; double &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20int64_5ft_20_3e_36',['sum_statistics&lt; int64_t &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]],
  ['sum_5fstatistics_3c_20std_3a_3astring_20_3e_37',['sum_statistics&lt; std::string &gt;',['../structcudf_1_1io_1_1sum__statistics.html',1,'cudf::io']]]
];
