var annotated_dup =
[
    [ "cudf", "namespacecudf.html", [
      [ "ast", "namespacecudf_1_1ast.html", [
        [ "detail", "namespacecudf_1_1ast_1_1detail.html", [
          [ "arity_functor", "structcudf_1_1ast_1_1detail_1_1arity__functor.html", "structcudf_1_1ast_1_1detail_1_1arity__functor" ],
          [ "cast", "structcudf_1_1ast_1_1detail_1_1cast.html", "structcudf_1_1ast_1_1detail_1_1cast" ],
          [ "device_data_reference", "structcudf_1_1ast_1_1detail_1_1device__data__reference.html", "structcudf_1_1ast_1_1detail_1_1device__data__reference" ],
          [ "dispatch_unary_operator_types", "structcudf_1_1ast_1_1detail_1_1dispatch__unary__operator__types.html", "structcudf_1_1ast_1_1detail_1_1dispatch__unary__operator__types" ],
          [ "expression_device_view", "structcudf_1_1ast_1_1detail_1_1expression__device__view.html", "structcudf_1_1ast_1_1detail_1_1expression__device__view" ],
          [ "expression_parser", "classcudf_1_1ast_1_1detail_1_1expression__parser.html", "classcudf_1_1ast_1_1detail_1_1expression__parser" ],
          [ "operator_functor", "structcudf_1_1ast_1_1detail_1_1operator__functor.html", null ],
          [ "operator_functor< ast_operator::ABS, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_b_s_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_b_s_00_01false_01_4" ],
          [ "operator_functor< ast_operator::ADD, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_d_d_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_d_d_00_01false_01_4" ],
          [ "operator_functor< ast_operator::ARCCOS, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_c_o_s_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_c_o_s_00_01false_01_4" ],
          [ "operator_functor< ast_operator::ARCCOSH, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_c_o_s_h_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_c_o_s_h_00_01false_01_4" ],
          [ "operator_functor< ast_operator::ARCSIN, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_s_i_n_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_s_i_n_00_01false_01_4" ],
          [ "operator_functor< ast_operator::ARCSINH, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_s_i_n_h_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_s_i_n_h_00_01false_01_4" ],
          [ "operator_functor< ast_operator::ARCTAN, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_t_a_n_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_t_a_n_00_01false_01_4" ],
          [ "operator_functor< ast_operator::ARCTANH, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_t_a_n_h_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_a_r_c_t_a_n_h_00_01false_01_4" ],
          [ "operator_functor< ast_operator::BIT_INVERT, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t___i_n_v_e_r_t_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t___i_n_v_e_r_t_00_01false_01_4" ],
          [ "operator_functor< ast_operator::BITWISE_AND, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t_w_i_s_e___a_n_d_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t_w_i_s_e___a_n_d_00_01false_01_4" ],
          [ "operator_functor< ast_operator::BITWISE_OR, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t_w_i_s_e___o_r_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t_w_i_s_e___o_r_00_01false_01_4" ],
          [ "operator_functor< ast_operator::BITWISE_XOR, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t_w_i_s_e___x_o_r_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_b_i_t_w_i_s_e___x_o_r_00_01false_01_4" ],
          [ "operator_functor< ast_operator::CAST_TO_FLOAT64, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_a_s_t___t_o___f_l_o_a_t64_00_01false_01_4.html", null ],
          [ "operator_functor< ast_operator::CAST_TO_INT64, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_a_s_t___t_o___i_n_t64_00_01false_01_4.html", null ],
          [ "operator_functor< ast_operator::CAST_TO_UINT64, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_a_s_t___t_o___u_i_n_t64_00_01false_01_4.html", null ],
          [ "operator_functor< ast_operator::CBRT, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_b_r_t_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_b_r_t_00_01false_01_4" ],
          [ "operator_functor< ast_operator::CEIL, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_e_i_l_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_e_i_l_00_01false_01_4" ],
          [ "operator_functor< ast_operator::COS, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_o_s_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_o_s_00_01false_01_4" ],
          [ "operator_functor< ast_operator::COSH, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_o_s_h_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_c_o_s_h_00_01false_01_4" ],
          [ "operator_functor< ast_operator::DIV, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_d_i_v_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_d_i_v_00_01false_01_4" ],
          [ "operator_functor< ast_operator::EQUAL, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_e_q_u_a_l_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_e_q_u_a_l_00_01false_01_4" ],
          [ "operator_functor< ast_operator::EXP, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_e_x_p_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_e_x_p_00_01false_01_4" ],
          [ "operator_functor< ast_operator::FLOOR, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_f_l_o_o_r_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_f_l_o_o_r_00_01false_01_4" ],
          [ "operator_functor< ast_operator::FLOOR_DIV, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_f_l_o_o_r___d_i_v_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_f_l_o_o_r___d_i_v_00_01false_01_4" ],
          [ "operator_functor< ast_operator::GREATER, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_g_r_e_a_t_e_r_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_g_r_e_a_t_e_r_00_01false_01_4" ],
          [ "operator_functor< ast_operator::GREATER_EQUAL, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_g_r_e_a_t_e_r___e_q_u_a_l_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_g_r_e_a_t_e_r___e_q_u_a_l_00_01false_01_4" ],
          [ "operator_functor< ast_operator::IDENTITY, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_i_d_e_n_t_i_t_y_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_i_d_e_n_t_i_t_y_00_01false_01_4" ],
          [ "operator_functor< ast_operator::LESS, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_e_s_s_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_e_s_s_00_01false_01_4" ],
          [ "operator_functor< ast_operator::LESS_EQUAL, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_e_s_s___e_q_u_a_l_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_e_s_s___e_q_u_a_l_00_01false_01_4" ],
          [ "operator_functor< ast_operator::LOG, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_o_g_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_o_g_00_01false_01_4" ],
          [ "operator_functor< ast_operator::LOGICAL_AND, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_o_g_i_c_a_l___a_n_d_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_o_g_i_c_a_l___a_n_d_00_01false_01_4" ],
          [ "operator_functor< ast_operator::LOGICAL_OR, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_o_g_i_c_a_l___o_r_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_l_o_g_i_c_a_l___o_r_00_01false_01_4" ],
          [ "operator_functor< ast_operator::MOD, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_m_o_d_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_m_o_d_00_01false_01_4" ],
          [ "operator_functor< ast_operator::MUL, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_m_u_l_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_m_u_l_00_01false_01_4" ],
          [ "operator_functor< ast_operator::NOT, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_o_t_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_o_t_00_01false_01_4" ],
          [ "operator_functor< ast_operator::NOT_EQUAL, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_o_t___e_q_u_a_l_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_o_t___e_q_u_a_l_00_01false_01_4" ],
          [ "operator_functor< ast_operator::NULL_EQUAL, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___e_q_u_a_l_00_01false_01_4.html", null ],
          [ "operator_functor< ast_operator::NULL_EQUAL, true >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___e_q_u_a_l_00_01true_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___e_q_u_a_l_00_01true_01_4" ],
          [ "operator_functor< ast_operator::NULL_LOGICAL_AND, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___l_o_g_i_c_a_l___a_n_d_00_01false_01_4.html", null ],
          [ "operator_functor< ast_operator::NULL_LOGICAL_AND, true >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___l_o_g_i_c_a_l___a_n_d_00_01true_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___l_o_g_i_c_a_l___a_n_d_00_01true_01_4" ],
          [ "operator_functor< ast_operator::NULL_LOGICAL_OR, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___l_o_g_i_c_a_l___o_r_00_01false_01_4.html", null ],
          [ "operator_functor< ast_operator::NULL_LOGICAL_OR, true >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___l_o_g_i_c_a_l___o_r_00_01true_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_n_u_l_l___l_o_g_i_c_a_l___o_r_00_01true_01_4" ],
          [ "operator_functor< ast_operator::POW, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_p_o_w_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_p_o_w_00_01false_01_4" ],
          [ "operator_functor< ast_operator::PYMOD, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_p_y_m_o_d_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_p_y_m_o_d_00_01false_01_4" ],
          [ "operator_functor< ast_operator::RINT, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_r_i_n_t_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_r_i_n_t_00_01false_01_4" ],
          [ "operator_functor< ast_operator::SIN, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_i_n_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_i_n_00_01false_01_4" ],
          [ "operator_functor< ast_operator::SINH, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_i_n_h_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_i_n_h_00_01false_01_4" ],
          [ "operator_functor< ast_operator::SQRT, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_q_r_t_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_q_r_t_00_01false_01_4" ],
          [ "operator_functor< ast_operator::SUB, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_u_b_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_s_u_b_00_01false_01_4" ],
          [ "operator_functor< ast_operator::TAN, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_t_a_n_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_t_a_n_00_01false_01_4" ],
          [ "operator_functor< ast_operator::TANH, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_t_a_n_h_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_t_a_n_h_00_01false_01_4" ],
          [ "operator_functor< ast_operator::TRUE_DIV, false >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_t_r_u_e___d_i_v_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01ast__operator_1_1_t_r_u_e___d_i_v_00_01false_01_4" ],
          [ "operator_functor< op, true >", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01op_00_01true_01_4.html", "structcudf_1_1ast_1_1detail_1_1operator__functor_3_01op_00_01true_01_4" ],
          [ "possibly_null_value", "structcudf_1_1ast_1_1detail_1_1possibly__null__value.html", null ],
          [ "possibly_null_value< T, false >", "structcudf_1_1ast_1_1detail_1_1possibly__null__value_3_01_t_00_01false_01_4.html", "structcudf_1_1ast_1_1detail_1_1possibly__null__value_3_01_t_00_01false_01_4" ],
          [ "possibly_null_value< T, true >", "structcudf_1_1ast_1_1detail_1_1possibly__null__value_3_01_t_00_01true_01_4.html", "structcudf_1_1ast_1_1detail_1_1possibly__null__value_3_01_t_00_01true_01_4" ],
          [ "return_type_functor", "structcudf_1_1ast_1_1detail_1_1return__type__functor.html", "structcudf_1_1ast_1_1detail_1_1return__type__functor" ],
          [ "single_dispatch_binary_operator_types", "structcudf_1_1ast_1_1detail_1_1single__dispatch__binary__operator__types.html", "structcudf_1_1ast_1_1detail_1_1single__dispatch__binary__operator__types" ],
          [ "type_dispatch_binary_op", "structcudf_1_1ast_1_1detail_1_1type__dispatch__binary__op.html", "structcudf_1_1ast_1_1detail_1_1type__dispatch__binary__op" ],
          [ "type_dispatch_unary_op", "structcudf_1_1ast_1_1detail_1_1type__dispatch__unary__op.html", "structcudf_1_1ast_1_1detail_1_1type__dispatch__unary__op" ]
        ] ],
        [ "column_reference", "classcudf_1_1ast_1_1column__reference.html", "classcudf_1_1ast_1_1column__reference" ],
        [ "expression", "structcudf_1_1ast_1_1expression.html", "structcudf_1_1ast_1_1expression" ],
        [ "literal", "classcudf_1_1ast_1_1literal.html", "classcudf_1_1ast_1_1literal" ],
        [ "operation", "classcudf_1_1ast_1_1operation.html", "classcudf_1_1ast_1_1operation" ]
      ] ],
      [ "detail", "namespacecudf_1_1detail.html", [
        [ "aggregation_finalizer", "classcudf_1_1detail_1_1aggregation__finalizer.html", "classcudf_1_1detail_1_1aggregation__finalizer" ],
        [ "all_aggregation", "classcudf_1_1detail_1_1all__aggregation.html", "classcudf_1_1detail_1_1all__aggregation" ],
        [ "any_aggregation", "classcudf_1_1detail_1_1any__aggregation.html", "classcudf_1_1detail_1_1any__aggregation" ],
        [ "argmax_aggregation", "classcudf_1_1detail_1_1argmax__aggregation.html", "classcudf_1_1detail_1_1argmax__aggregation" ],
        [ "argmin_aggregation", "classcudf_1_1detail_1_1argmin__aggregation.html", "classcudf_1_1detail_1_1argmin__aggregation" ],
        [ "base_2dspan", "classcudf_1_1detail_1_1base__2dspan.html", "classcudf_1_1detail_1_1base__2dspan" ],
        [ "collect_list_aggregation", "classcudf_1_1detail_1_1collect__list__aggregation.html", "classcudf_1_1detail_1_1collect__list__aggregation" ],
        [ "collect_set_aggregation", "classcudf_1_1detail_1_1collect__set__aggregation.html", "classcudf_1_1detail_1_1collect__set__aggregation" ],
        [ "column_view_base", "classcudf_1_1detail_1_1column__view__base.html", "classcudf_1_1detail_1_1column__view__base" ],
        [ "correlation_aggregation", "classcudf_1_1detail_1_1correlation__aggregation.html", "classcudf_1_1detail_1_1correlation__aggregation" ],
        [ "count_aggregation", "classcudf_1_1detail_1_1count__aggregation.html", "classcudf_1_1detail_1_1count__aggregation" ],
        [ "covariance_aggregation", "classcudf_1_1detail_1_1covariance__aggregation.html", "classcudf_1_1detail_1_1covariance__aggregation" ],
        [ "dispatch_aggregation", "structcudf_1_1detail_1_1dispatch__aggregation.html", "structcudf_1_1detail_1_1dispatch__aggregation" ],
        [ "dispatch_source", "structcudf_1_1detail_1_1dispatch__source.html", "structcudf_1_1detail_1_1dispatch__source" ],
        [ "dremel_data", "structcudf_1_1detail_1_1dremel__data.html", "structcudf_1_1detail_1_1dremel__data" ],
        [ "dremel_device_view", "structcudf_1_1detail_1_1dremel__device__view.html", "structcudf_1_1detail_1_1dremel__device__view" ],
        [ "fixed_width_scalar", "classcudf_1_1detail_1_1fixed__width__scalar.html", "classcudf_1_1detail_1_1fixed__width__scalar" ],
        [ "has_common_type_impl", "structcudf_1_1detail_1_1has__common__type__impl.html", null ],
        [ "has_common_type_impl< void_t< std::common_type_t< Ts... > >, Ts... >", "structcudf_1_1detail_1_1has__common__type__impl_3_01void__t_3_01std_1_1common__type__t_3_01_ts_8e2d33eab3ad4b77e8506b3fe056aacf5.html", null ],
        [ "hash_join", "structcudf_1_1detail_1_1hash__join.html", "structcudf_1_1detail_1_1hash__join" ],
        [ "is_equality_comparable_impl", "structcudf_1_1detail_1_1is__equality__comparable__impl.html", null ],
        [ "is_equality_comparable_impl< L, R, void_t< equality_comparable< L, R > > >", "structcudf_1_1detail_1_1is__equality__comparable__impl_3_01_l_00_01_r_00_01void__t_3_01equality_2f83d168aaedf92541e7f7f4a1af5cfa.html", null ],
        [ "is_relationally_comparable_impl", "structcudf_1_1detail_1_1is__relationally__comparable__impl.html", null ],
        [ "is_relationally_comparable_impl< L, R, void_t< less_comparable< L, R >, greater_comparable< L, R > > >", "structcudf_1_1detail_1_1is__relationally__comparable__impl_3_01_l_00_01_r_00_01void__t_3_01less_58b6dd73ceb6a464bcab762425ace104.html", null ],
        [ "kind_to_type_impl", "structcudf_1_1detail_1_1kind__to__type__impl.html", "structcudf_1_1detail_1_1kind__to__type__impl" ],
        [ "lead_lag_aggregation", "classcudf_1_1detail_1_1lead__lag__aggregation.html", "classcudf_1_1detail_1_1lead__lag__aggregation" ],
        [ "linked_column_view", "structcudf_1_1detail_1_1linked__column__view.html", "structcudf_1_1detail_1_1linked__column__view" ],
        [ "m2_aggregation", "classcudf_1_1detail_1_1m2__aggregation.html", "classcudf_1_1detail_1_1m2__aggregation" ],
        [ "max_aggregation", "classcudf_1_1detail_1_1max__aggregation.html", "classcudf_1_1detail_1_1max__aggregation" ],
        [ "mean_aggregation", "classcudf_1_1detail_1_1mean__aggregation.html", "classcudf_1_1detail_1_1mean__aggregation" ],
        [ "median_aggregation", "classcudf_1_1detail_1_1median__aggregation.html", "classcudf_1_1detail_1_1median__aggregation" ],
        [ "merge_lists_aggregation", "classcudf_1_1detail_1_1merge__lists__aggregation.html", "classcudf_1_1detail_1_1merge__lists__aggregation" ],
        [ "merge_m2_aggregation", "classcudf_1_1detail_1_1merge__m2__aggregation.html", "classcudf_1_1detail_1_1merge__m2__aggregation" ],
        [ "merge_sets_aggregation", "classcudf_1_1detail_1_1merge__sets__aggregation.html", "classcudf_1_1detail_1_1merge__sets__aggregation" ],
        [ "merge_tdigest_aggregation", "classcudf_1_1detail_1_1merge__tdigest__aggregation.html", "classcudf_1_1detail_1_1merge__tdigest__aggregation" ],
        [ "min_aggregation", "classcudf_1_1detail_1_1min__aggregation.html", "classcudf_1_1detail_1_1min__aggregation" ],
        [ "MurmurHash3_32", "classcudf_1_1detail_1_1_murmur_hash3__32.html", null ],
        [ "mutable_column_view_base", "classcudf_1_1detail_1_1mutable__column__view__base.html", null ],
        [ "nth_element_aggregation", "classcudf_1_1detail_1_1nth__element__aggregation.html", "classcudf_1_1detail_1_1nth__element__aggregation" ],
        [ "nunique_aggregation", "classcudf_1_1detail_1_1nunique__aggregation.html", "classcudf_1_1detail_1_1nunique__aggregation" ],
        [ "pair_column_aggregation_equal_to", "structcudf_1_1detail_1_1pair__column__aggregation__equal__to.html", "structcudf_1_1detail_1_1pair__column__aggregation__equal__to" ],
        [ "pair_column_aggregation_hash", "structcudf_1_1detail_1_1pair__column__aggregation__hash.html", "structcudf_1_1detail_1_1pair__column__aggregation__hash" ],
        [ "pinned_allocator", "classcudf_1_1detail_1_1pinned__allocator.html", "classcudf_1_1detail_1_1pinned__allocator" ],
        [ "pinned_allocator< void >", "classcudf_1_1detail_1_1pinned__allocator_3_01void_01_4.html", "classcudf_1_1detail_1_1pinned__allocator_3_01void_01_4" ],
        [ "product_aggregation", "classcudf_1_1detail_1_1product__aggregation.html", "classcudf_1_1detail_1_1product__aggregation" ],
        [ "quantile_aggregation", "classcudf_1_1detail_1_1quantile__aggregation.html", "classcudf_1_1detail_1_1quantile__aggregation" ],
        [ "rank_aggregation", "classcudf_1_1detail_1_1rank__aggregation.html", "classcudf_1_1detail_1_1rank__aggregation" ],
        [ "result_cache", "classcudf_1_1detail_1_1result__cache.html", "classcudf_1_1detail_1_1result__cache" ],
        [ "row_number_aggregation", "classcudf_1_1detail_1_1row__number__aggregation.html", "classcudf_1_1detail_1_1row__number__aggregation" ],
        [ "simple_aggregations_collector", "classcudf_1_1detail_1_1simple__aggregations__collector.html", "classcudf_1_1detail_1_1simple__aggregations__collector" ],
        [ "span_base", "classcudf_1_1detail_1_1span__base.html", "classcudf_1_1detail_1_1span__base" ],
        [ "std_aggregation", "classcudf_1_1detail_1_1std__aggregation.html", "classcudf_1_1detail_1_1std__aggregation" ],
        [ "std_var_aggregation", "classcudf_1_1detail_1_1std__var__aggregation.html", "classcudf_1_1detail_1_1std__var__aggregation" ],
        [ "sum_aggregation", "classcudf_1_1detail_1_1sum__aggregation.html", "classcudf_1_1detail_1_1sum__aggregation" ],
        [ "sum_of_squares_aggregation", "classcudf_1_1detail_1_1sum__of__squares__aggregation.html", "classcudf_1_1detail_1_1sum__of__squares__aggregation" ],
        [ "table_view_base", "classcudf_1_1detail_1_1table__view__base.html", "classcudf_1_1detail_1_1table__view__base" ],
        [ "target_type_impl", "structcudf_1_1detail_1_1target__type__impl.html", "structcudf_1_1detail_1_1target__type__impl" ],
        [ "target_type_impl< Source, aggregation::ALL >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_l_l_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_l_l_01_4" ],
        [ "target_type_impl< Source, aggregation::ANY >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_n_y_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_n_y_01_4" ],
        [ "target_type_impl< Source, aggregation::ARGMAX >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_r_g_m_a_x_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_r_g_m_a_x_01_4" ],
        [ "target_type_impl< Source, aggregation::ARGMIN >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_r_g_m_i_n_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_a_r_g_m_i_n_01_4" ],
        [ "target_type_impl< Source, aggregation::COLLECT_LIST >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_l_l_e_c_t___l_i_s_t_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_l_l_e_c_t___l_i_s_t_01_4" ],
        [ "target_type_impl< Source, aggregation::COLLECT_SET >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_l_l_e_c_t___s_e_t_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_l_l_e_c_t___s_e_t_01_4" ],
        [ "target_type_impl< Source, aggregation::COUNT_ALL >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_u_n_t___a_l_l_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_u_n_t___a_l_l_01_4" ],
        [ "target_type_impl< Source, aggregation::COUNT_VALID >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_u_n_t___v_a_l_i_d_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_c_o_u_n_t___v_a_l_i_d_01_4" ],
        [ "target_type_impl< Source, aggregation::LAG >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_l_a_g_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_l_a_g_01_4" ],
        [ "target_type_impl< Source, aggregation::LEAD >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_l_e_a_d_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_l_e_a_d_01_4" ],
        [ "target_type_impl< Source, aggregation::MAX >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_a_x_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_a_x_01_4" ],
        [ "target_type_impl< Source, aggregation::MEDIAN >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_d_i_a_n_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_d_i_a_n_01_4" ],
        [ "target_type_impl< Source, aggregation::MERGE_LISTS >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_r_g_e___l_i_s_t_s_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_r_g_e___l_i_s_t_s_01_4" ],
        [ "target_type_impl< Source, aggregation::MERGE_SETS >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_r_g_e___s_e_t_s_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_r_g_e___s_e_t_s_01_4" ],
        [ "target_type_impl< Source, aggregation::MERGE_TDIGEST, std::enable_if_t< std::is_same_v< Source, cudf::struct_view > > >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_r_g_e___t_d_i_g_b6032354e9dd2aab59ead12451496ee9.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_e_r_g_e___t_d_i_g_b6032354e9dd2aab59ead12451496ee9" ],
        [ "target_type_impl< Source, aggregation::MIN >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_i_n_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_m_i_n_01_4" ],
        [ "target_type_impl< Source, aggregation::NTH_ELEMENT >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_n_t_h___e_l_e_m_e_n_t_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_n_t_h___e_l_e_m_e_n_t_01_4" ],
        [ "target_type_impl< Source, aggregation::NUNIQUE >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_n_u_n_i_q_u_e_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_n_u_n_i_q_u_e_01_4" ],
        [ "target_type_impl< Source, aggregation::QUANTILE >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_q_u_a_n_t_i_l_e_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_q_u_a_n_t_i_l_e_01_4" ],
        [ "target_type_impl< Source, aggregation::RANK >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_r_a_n_k_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_r_a_n_k_01_4" ],
        [ "target_type_impl< Source, aggregation::ROW_NUMBER >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_r_o_w___n_u_m_b_e_r_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_r_o_w___n_u_m_b_e_r_01_4" ],
        [ "target_type_impl< Source, aggregation::TDIGEST, std::enable_if_t<(is_numeric< Source >()||is_fixed_point< Source >())> >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_t_d_i_g_e_s_t_00_01s5303a4b781861b9f20be89a332eefbb3.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01aggregation_1_1_t_d_i_g_e_s_t_00_01s5303a4b781861b9f20be89a332eefbb3" ],
        [ "target_type_impl< Source, k, std::enable_if_t< cudf::is_fixed_point< Source >() &&(k==aggregation::SUM)> >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01cudf860e3aa1a79ad60d80ae0d253e598b65.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01cudf860e3aa1a79ad60d80ae0d253e598b65" ],
        [ "target_type_impl< Source, k, std::enable_if_t< is_chrono< Source >() &&is_sum_product_agg(k)> >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01is__f22763bdc33c531f694b84a688c4178a.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01is__f22763bdc33c531f694b84a688c4178a" ],
        [ "target_type_impl< Source, k, std::enable_if_t< is_fixed_width< Source >() and not is_chrono< Source >() and not is_fixed_point< Source >() and(k==aggregation::MEAN)> >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01is__a2b4cf18bf67fdbe4602b98faf0157b3.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01is__a2b4cf18bf67fdbe4602b98faf0157b3" ],
        [ "target_type_impl< Source, k, std::enable_if_t< std::is_floating_point_v< Source > &&is_sum_product_agg(k)> >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01std_9f689773868603c824fb593bd3e5e573.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01std_9f689773868603c824fb593bd3e5e573" ],
        [ "target_type_impl< Source, k, std::enable_if_t< std::is_integral_v< Source > &&is_sum_product_agg(k)> >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01std_eb928db258a099e4b94f2dc9fe8c0a44.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_01std_eb928db258a099e4b94f2dc9fe8c0a44" ],
        [ "target_type_impl< Source, k, std::enable_if_t<(is_chrono< Source >() or is_fixed_point< Source >()) &&(k==aggregation::MEAN)> >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_07is__2d246396d9b567139696a42c8c67e9c9.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_00_01k_00_01std_1_1enable__if__t_3_07is__2d246396d9b567139696a42c8c67e9c9" ],
        [ "target_type_impl< SourceType, aggregation::CORRELATION >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_c_o_r_r_e_l_a_t_i_o_n_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_c_o_r_r_e_l_a_t_i_o_n_01_4" ],
        [ "target_type_impl< SourceType, aggregation::COVARIANCE >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_c_o_v_a_r_i_a_n_c_e_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_c_o_v_a_r_i_a_n_c_e_01_4" ],
        [ "target_type_impl< SourceType, aggregation::M2 >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_m2_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_m2_01_4" ],
        [ "target_type_impl< SourceType, aggregation::MERGE_M2 >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_m_e_r_g_e___m2_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_m_e_r_g_e___m2_01_4" ],
        [ "target_type_impl< SourceType, aggregation::STD >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_s_t_d_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_s_t_d_01_4" ],
        [ "target_type_impl< SourceType, aggregation::VARIANCE >", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_v_a_r_i_a_n_c_e_01_4.html", "structcudf_1_1detail_1_1target__type__impl_3_01_source_type_00_01aggregation_1_1_v_a_r_i_a_n_c_e_01_4" ],
        [ "tdigest_aggregation", "classcudf_1_1detail_1_1tdigest__aggregation.html", "classcudf_1_1detail_1_1tdigest__aggregation" ],
        [ "udf_aggregation", "classcudf_1_1detail_1_1udf__aggregation.html", "classcudf_1_1detail_1_1udf__aggregation" ],
        [ "var_aggregation", "classcudf_1_1detail_1_1var__aggregation.html", "classcudf_1_1detail_1_1var__aggregation" ],
        [ "visitor_overload", "structcudf_1_1detail_1_1visitor__overload.html", null ]
      ] ],
      [ "groupby", "namespacecudf_1_1groupby.html", [
        [ "detail", "namespacecudf_1_1groupby_1_1detail.html", [
          [ "sort", "namespacecudf_1_1groupby_1_1detail_1_1sort.html", [
            [ "sort_groupby_helper", "structcudf_1_1groupby_1_1detail_1_1sort_1_1sort__groupby__helper.html", "structcudf_1_1groupby_1_1detail_1_1sort_1_1sort__groupby__helper" ]
          ] ]
        ] ],
        [ "aggregation_request", "structcudf_1_1groupby_1_1aggregation__request.html", "structcudf_1_1groupby_1_1aggregation__request" ],
        [ "aggregation_result", "structcudf_1_1groupby_1_1aggregation__result.html", "structcudf_1_1groupby_1_1aggregation__result" ],
        [ "groupby", "classcudf_1_1groupby_1_1groupby.html", "classcudf_1_1groupby_1_1groupby" ],
        [ "scan_request", "structcudf_1_1groupby_1_1scan__request.html", "structcudf_1_1groupby_1_1scan__request" ]
      ] ],
      [ "io", "namespacecudf_1_1io.html", [
        [ "detail", "namespacecudf_1_1io_1_1detail.html", [
          [ "orc", "namespacecudf_1_1io_1_1detail_1_1orc.html", [
            [ "reader", "classcudf_1_1io_1_1detail_1_1orc_1_1reader.html", "classcudf_1_1io_1_1detail_1_1orc_1_1reader" ],
            [ "writer", "classcudf_1_1io_1_1detail_1_1orc_1_1writer.html", "classcudf_1_1io_1_1detail_1_1orc_1_1writer" ]
          ] ],
          [ "parquet", "namespacecudf_1_1io_1_1detail_1_1parquet.html", [
            [ "chunked_reader", "classcudf_1_1io_1_1detail_1_1parquet_1_1chunked__reader.html", "classcudf_1_1io_1_1detail_1_1parquet_1_1chunked__reader" ],
            [ "reader", "classcudf_1_1io_1_1detail_1_1parquet_1_1reader.html", "classcudf_1_1io_1_1detail_1_1parquet_1_1reader" ],
            [ "writer", "classcudf_1_1io_1_1detail_1_1parquet_1_1writer.html", "classcudf_1_1io_1_1detail_1_1parquet_1_1writer" ]
          ] ]
        ] ],
        [ "text", "namespacecudf_1_1io_1_1text.html", [
          [ "detail", "namespacecudf_1_1io_1_1text_1_1detail.html", [
            [ "bgzip", "namespacecudf_1_1io_1_1text_1_1detail_1_1bgzip.html", [
              [ "footer", "structcudf_1_1io_1_1text_1_1detail_1_1bgzip_1_1footer.html", "structcudf_1_1io_1_1text_1_1detail_1_1bgzip_1_1footer" ],
              [ "header", "structcudf_1_1io_1_1text_1_1detail_1_1bgzip_1_1header.html", "structcudf_1_1io_1_1text_1_1detail_1_1bgzip_1_1header" ]
            ] ],
            [ "multistate", "structcudf_1_1io_1_1text_1_1detail_1_1multistate.html", "structcudf_1_1io_1_1text_1_1detail_1_1multistate" ],
            [ "scan_tile_state", "structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state.html", "structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state" ],
            [ "scan_tile_state_callback", "structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state__callback.html", "structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state__callback" ],
            [ "scan_tile_state_view", "structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state__view.html", "structcudf_1_1io_1_1text_1_1detail_1_1scan__tile__state__view" ],
            [ "trie", "structcudf_1_1io_1_1text_1_1detail_1_1trie.html", "structcudf_1_1io_1_1text_1_1detail_1_1trie" ],
            [ "trie_device_view", "structcudf_1_1io_1_1text_1_1detail_1_1trie__device__view.html", "structcudf_1_1io_1_1text_1_1detail_1_1trie__device__view" ],
            [ "trie_node", "structcudf_1_1io_1_1text_1_1detail_1_1trie__node.html", "structcudf_1_1io_1_1text_1_1detail_1_1trie__node" ]
          ] ],
          [ "byte_range_info", "classcudf_1_1io_1_1text_1_1byte__range__info.html", "classcudf_1_1io_1_1text_1_1byte__range__info" ],
          [ "data_chunk_reader", "classcudf_1_1io_1_1text_1_1data__chunk__reader.html", "classcudf_1_1io_1_1text_1_1data__chunk__reader" ],
          [ "data_chunk_source", "classcudf_1_1io_1_1text_1_1data__chunk__source.html", "classcudf_1_1io_1_1text_1_1data__chunk__source" ],
          [ "device_data_chunk", "classcudf_1_1io_1_1text_1_1device__data__chunk.html", "classcudf_1_1io_1_1text_1_1device__data__chunk" ],
          [ "parse_options", "structcudf_1_1io_1_1text_1_1parse__options.html", "structcudf_1_1io_1_1text_1_1parse__options" ]
        ] ],
        [ "arrow_io_source", "classcudf_1_1io_1_1arrow__io__source.html", "classcudf_1_1io_1_1arrow__io__source" ],
        [ "avro_reader_options", "classcudf_1_1io_1_1avro__reader__options.html", "classcudf_1_1io_1_1avro__reader__options" ],
        [ "avro_reader_options_builder", "classcudf_1_1io_1_1avro__reader__options__builder.html", "classcudf_1_1io_1_1avro__reader__options__builder" ],
        [ "bucket_statistics", "structcudf_1_1io_1_1bucket__statistics.html", "structcudf_1_1io_1_1bucket__statistics" ],
        [ "chunked_orc_writer_options", "classcudf_1_1io_1_1chunked__orc__writer__options.html", "classcudf_1_1io_1_1chunked__orc__writer__options" ],
        [ "chunked_orc_writer_options_builder", "classcudf_1_1io_1_1chunked__orc__writer__options__builder.html", "classcudf_1_1io_1_1chunked__orc__writer__options__builder" ],
        [ "chunked_parquet_reader", "classcudf_1_1io_1_1chunked__parquet__reader.html", "classcudf_1_1io_1_1chunked__parquet__reader" ],
        [ "chunked_parquet_writer_options", "classcudf_1_1io_1_1chunked__parquet__writer__options.html", "classcudf_1_1io_1_1chunked__parquet__writer__options" ],
        [ "chunked_parquet_writer_options_builder", "classcudf_1_1io_1_1chunked__parquet__writer__options__builder.html", "classcudf_1_1io_1_1chunked__parquet__writer__options__builder" ],
        [ "column_in_metadata", "classcudf_1_1io_1_1column__in__metadata.html", "classcudf_1_1io_1_1column__in__metadata" ],
        [ "column_name_info", "structcudf_1_1io_1_1column__name__info.html", "structcudf_1_1io_1_1column__name__info" ],
        [ "column_statistics", "structcudf_1_1io_1_1column__statistics.html", "structcudf_1_1io_1_1column__statistics" ],
        [ "csv_reader_options", "classcudf_1_1io_1_1csv__reader__options.html", "classcudf_1_1io_1_1csv__reader__options" ],
        [ "csv_reader_options_builder", "classcudf_1_1io_1_1csv__reader__options__builder.html", "classcudf_1_1io_1_1csv__reader__options__builder" ],
        [ "csv_writer_options", "classcudf_1_1io_1_1csv__writer__options.html", "classcudf_1_1io_1_1csv__writer__options" ],
        [ "csv_writer_options_builder", "classcudf_1_1io_1_1csv__writer__options__builder.html", "classcudf_1_1io_1_1csv__writer__options__builder" ],
        [ "data_sink", "classcudf_1_1io_1_1data__sink.html", "classcudf_1_1io_1_1data__sink" ],
        [ "datasource", "classcudf_1_1io_1_1datasource.html", "classcudf_1_1io_1_1datasource" ],
        [ "decimal_statistics", "structcudf_1_1io_1_1decimal__statistics.html", null ],
        [ "double_statistics", "structcudf_1_1io_1_1double__statistics.html", null ],
        [ "host_buffer", "structcudf_1_1io_1_1host__buffer.html", "structcudf_1_1io_1_1host__buffer" ],
        [ "integer_statistics", "structcudf_1_1io_1_1integer__statistics.html", null ],
        [ "json_reader_options", "classcudf_1_1io_1_1json__reader__options.html", "classcudf_1_1io_1_1json__reader__options" ],
        [ "json_reader_options_builder", "classcudf_1_1io_1_1json__reader__options__builder.html", "classcudf_1_1io_1_1json__reader__options__builder" ],
        [ "minmax_statistics", "structcudf_1_1io_1_1minmax__statistics.html", "structcudf_1_1io_1_1minmax__statistics" ],
        [ "orc_chunked_writer", "classcudf_1_1io_1_1orc__chunked__writer.html", "classcudf_1_1io_1_1orc__chunked__writer" ],
        [ "orc_column_schema", "structcudf_1_1io_1_1orc__column__schema.html", "structcudf_1_1io_1_1orc__column__schema" ],
        [ "orc_metadata", "classcudf_1_1io_1_1orc__metadata.html", "classcudf_1_1io_1_1orc__metadata" ],
        [ "orc_reader_options", "classcudf_1_1io_1_1orc__reader__options.html", "classcudf_1_1io_1_1orc__reader__options" ],
        [ "orc_reader_options_builder", "classcudf_1_1io_1_1orc__reader__options__builder.html", "classcudf_1_1io_1_1orc__reader__options__builder" ],
        [ "orc_schema", "structcudf_1_1io_1_1orc__schema.html", "structcudf_1_1io_1_1orc__schema" ],
        [ "orc_writer_options", "classcudf_1_1io_1_1orc__writer__options.html", "classcudf_1_1io_1_1orc__writer__options" ],
        [ "orc_writer_options_builder", "classcudf_1_1io_1_1orc__writer__options__builder.html", "classcudf_1_1io_1_1orc__writer__options__builder" ],
        [ "parquet_chunked_writer", "classcudf_1_1io_1_1parquet__chunked__writer.html", "classcudf_1_1io_1_1parquet__chunked__writer" ],
        [ "parquet_reader_options", "classcudf_1_1io_1_1parquet__reader__options.html", "classcudf_1_1io_1_1parquet__reader__options" ],
        [ "parquet_reader_options_builder", "classcudf_1_1io_1_1parquet__reader__options__builder.html", "classcudf_1_1io_1_1parquet__reader__options__builder" ],
        [ "parquet_writer_options", "classcudf_1_1io_1_1parquet__writer__options.html", "classcudf_1_1io_1_1parquet__writer__options" ],
        [ "parquet_writer_options_builder", "classcudf_1_1io_1_1parquet__writer__options__builder.html", "classcudf_1_1io_1_1parquet__writer__options__builder" ],
        [ "parsed_orc_statistics", "structcudf_1_1io_1_1parsed__orc__statistics.html", "structcudf_1_1io_1_1parsed__orc__statistics" ],
        [ "partition_info", "structcudf_1_1io_1_1partition__info.html", "structcudf_1_1io_1_1partition__info" ],
        [ "raw_orc_statistics", "structcudf_1_1io_1_1raw__orc__statistics.html", "structcudf_1_1io_1_1raw__orc__statistics" ],
        [ "reader_column_schema", "classcudf_1_1io_1_1reader__column__schema.html", "classcudf_1_1io_1_1reader__column__schema" ],
        [ "schema_element", "structcudf_1_1io_1_1schema__element.html", "structcudf_1_1io_1_1schema__element" ],
        [ "sink_info", "structcudf_1_1io_1_1sink__info.html", "structcudf_1_1io_1_1sink__info" ],
        [ "source_info", "structcudf_1_1io_1_1source__info.html", "structcudf_1_1io_1_1source__info" ],
        [ "string_statistics", "structcudf_1_1io_1_1string__statistics.html", null ],
        [ "sum_statistics", "structcudf_1_1io_1_1sum__statistics.html", "structcudf_1_1io_1_1sum__statistics" ],
        [ "table_input_metadata", "classcudf_1_1io_1_1table__input__metadata.html", "classcudf_1_1io_1_1table__input__metadata" ],
        [ "table_metadata", "structcudf_1_1io_1_1table__metadata.html", "structcudf_1_1io_1_1table__metadata" ],
        [ "table_with_metadata", "structcudf_1_1io_1_1table__with__metadata.html", "structcudf_1_1io_1_1table__with__metadata" ],
        [ "timestamp_statistics", "structcudf_1_1io_1_1timestamp__statistics.html", "structcudf_1_1io_1_1timestamp__statistics" ]
      ] ],
      [ "strings", "namespacecudf_1_1strings.html", [
        [ "detail", "namespacecudf_1_1strings_1_1detail.html", [
          [ "special_case_mapping", "structcudf_1_1strings_1_1detail_1_1special__case__mapping.html", "structcudf_1_1strings_1_1detail_1_1special__case__mapping" ]
        ] ],
        [ "get_json_object_options", "classcudf_1_1strings_1_1get__json__object__options.html", "classcudf_1_1strings_1_1get__json__object__options" ],
        [ "regex_program", "structcudf_1_1strings_1_1regex__program.html", "structcudf_1_1strings_1_1regex__program" ]
      ] ],
      [ "structs", "namespacecudf_1_1structs.html", [
        [ "detail", "namespacecudf_1_1structs_1_1detail.html", [
          [ "flattened_table", "classcudf_1_1structs_1_1detail_1_1flattened__table.html", "classcudf_1_1structs_1_1detail_1_1flattened__table" ]
        ] ]
      ] ],
      [ "tdigest", "namespacecudf_1_1tdigest.html", [
        [ "tdigest_column_view", "classcudf_1_1tdigest_1_1tdigest__column__view.html", "classcudf_1_1tdigest_1_1tdigest__column__view" ]
      ] ],
      [ "aggregation", "classcudf_1_1aggregation.html", "classcudf_1_1aggregation" ],
      [ "chrono_scalar", "classcudf_1_1chrono__scalar.html", "classcudf_1_1chrono__scalar" ],
      [ "column", "classcudf_1_1column.html", "classcudf_1_1column" ],
      [ "column_metadata", "structcudf_1_1column__metadata.html", "structcudf_1_1column__metadata" ],
      [ "column_view", "classcudf_1_1column__view.html", "classcudf_1_1column__view" ],
      [ "cuda_error", "structcudf_1_1cuda__error.html", "structcudf_1_1cuda__error" ],
      [ "data_type", "classcudf_1_1data__type.html", "classcudf_1_1data__type" ],
      [ "device_span", "structcudf_1_1device__span.html", "structcudf_1_1device__span" ],
      [ "dictionary_column_view", "classcudf_1_1dictionary__column__view.html", "classcudf_1_1dictionary__column__view" ],
      [ "dictionary_wrapper", "structcudf_1_1dictionary__wrapper.html", "structcudf_1_1dictionary__wrapper" ],
      [ "dispatch_storage_type", "structcudf_1_1dispatch__storage__type.html", "structcudf_1_1dispatch__storage__type" ],
      [ "duration_scalar", "classcudf_1_1duration__scalar.html", "classcudf_1_1duration__scalar" ],
      [ "duration_scalar_device_view", "classcudf_1_1duration__scalar__device__view.html", null ],
      [ "fatal_cuda_error", "structcudf_1_1fatal__cuda__error.html", "structcudf_1_1fatal__cuda__error" ],
      [ "fixed_point_scalar", "classcudf_1_1fixed__point__scalar.html", "classcudf_1_1fixed__point__scalar" ],
      [ "fixed_point_scalar_device_view", "classcudf_1_1fixed__point__scalar__device__view.html", null ],
      [ "groupby_aggregation", "classcudf_1_1groupby__aggregation.html", "classcudf_1_1groupby__aggregation" ],
      [ "groupby_scan_aggregation", "classcudf_1_1groupby__scan__aggregation.html", "classcudf_1_1groupby__scan__aggregation" ],
      [ "hash_join", "classcudf_1_1hash__join.html", "classcudf_1_1hash__join" ],
      [ "host_span", "structcudf_1_1host__span.html", "structcudf_1_1host__span" ],
      [ "id_to_type_impl", "structcudf_1_1id__to__type__impl.html", "structcudf_1_1id__to__type__impl" ],
      [ "is_convertible", "structcudf_1_1is__convertible.html", null ],
      [ "is_convertible< cudf::detail::timestamp< Duration1 >, cudf::detail::timestamp< Duration2 > >", "structcudf_1_1is__convertible_3_01cudf_1_1detail_1_1timestamp_3_01_duration1_01_4_00_01cudf_1_1daa0b9b43387383cde2e3c74f3ffafc24.html", null ],
      [ "is_device_span_supported_container", "structcudf_1_1is__device__span__supported__container.html", null ],
      [ "is_device_span_supported_container< rmm::device_uvector< T > >", "structcudf_1_1is__device__span__supported__container_3_01rmm_1_1device__uvector_3_01_t_01_4_01_4.html", null ],
      [ "is_device_span_supported_container< rmm::device_vector< T > >", "structcudf_1_1is__device__span__supported__container_3_01rmm_1_1device__vector_3_01_t_01_4_01_4.html", null ],
      [ "is_device_span_supported_container< thrust::device_vector< T, Alloc > >", "structcudf_1_1is__device__span__supported__container_3_01thrust_1_1device__vector_3_01_t_00_01_alloc_01_4_01_4.html", null ],
      [ "is_host_span_supported_container", "structcudf_1_1is__host__span__supported__container.html", null ],
      [ "is_host_span_supported_container< std::basic_string< T, std::char_traits< T >, Alloc > >", "structcudf_1_1is__host__span__supported__container_3_01std_1_1basic__string_3_01_t_00_01std_1_1c61bc91e581171fc0cf8b4a95db4a7c39.html", null ],
      [ "is_host_span_supported_container< std::vector< T, Alloc > >", "structcudf_1_1is__host__span__supported__container_3_01std_1_1vector_3_01_t_00_01_alloc_01_4_01_4.html", null ],
      [ "is_host_span_supported_container< thrust::host_vector< T, Alloc > >", "structcudf_1_1is__host__span__supported__container_3_01thrust_1_1host__vector_3_01_t_00_01_alloc_01_4_01_4.html", null ],
      [ "libcudf_domain", "structcudf_1_1libcudf__domain.html", "structcudf_1_1libcudf__domain" ],
      [ "list_scalar", "classcudf_1_1list__scalar.html", "classcudf_1_1list__scalar" ],
      [ "list_view", "classcudf_1_1list__view.html", null ],
      [ "lists_column_view", "classcudf_1_1lists__column__view.html", "classcudf_1_1lists__column__view" ],
      [ "logic_error", "structcudf_1_1logic__error.html", "structcudf_1_1logic__error" ],
      [ "mutable_column_view", "classcudf_1_1mutable__column__view.html", "classcudf_1_1mutable__column__view" ],
      [ "mutable_table_view", "classcudf_1_1mutable__table__view.html", "classcudf_1_1mutable__table__view" ],
      [ "numeric_scalar", "classcudf_1_1numeric__scalar.html", "classcudf_1_1numeric__scalar" ],
      [ "numeric_scalar_device_view", "classcudf_1_1numeric__scalar__device__view.html", null ],
      [ "order_info", "structcudf_1_1order__info.html", "structcudf_1_1order__info" ],
      [ "packed_columns", "structcudf_1_1packed__columns.html", "structcudf_1_1packed__columns" ],
      [ "packed_table", "structcudf_1_1packed__table.html", "structcudf_1_1packed__table" ],
      [ "range_window_bounds", "structcudf_1_1range__window__bounds.html", "structcudf_1_1range__window__bounds" ],
      [ "reduce_aggregation", "classcudf_1_1reduce__aggregation.html", "classcudf_1_1reduce__aggregation" ],
      [ "rolling_aggregation", "classcudf_1_1rolling__aggregation.html", "classcudf_1_1rolling__aggregation" ],
      [ "scalar", "classcudf_1_1scalar.html", "classcudf_1_1scalar" ],
      [ "scan_aggregation", "classcudf_1_1scan__aggregation.html", "classcudf_1_1scan__aggregation" ],
      [ "segmented_reduce_aggregation", "classcudf_1_1segmented__reduce__aggregation.html", "classcudf_1_1segmented__reduce__aggregation" ],
      [ "string_scalar", "classcudf_1_1string__scalar.html", "classcudf_1_1string__scalar" ],
      [ "string_view", "classcudf_1_1string__view.html", "classcudf_1_1string__view" ],
      [ "strings_column_view", "classcudf_1_1strings__column__view.html", "classcudf_1_1strings__column__view" ],
      [ "struct_scalar", "classcudf_1_1struct__scalar.html", "classcudf_1_1struct__scalar" ],
      [ "struct_view", "classcudf_1_1struct__view.html", null ],
      [ "structs_column_view", "classcudf_1_1structs__column__view.html", "classcudf_1_1structs__column__view" ],
      [ "table", "classcudf_1_1table.html", "classcudf_1_1table" ],
      [ "table_view", "classcudf_1_1table__view.html", "classcudf_1_1table__view" ],
      [ "timestamp_scalar", "classcudf_1_1timestamp__scalar.html", "classcudf_1_1timestamp__scalar" ],
      [ "timestamp_scalar_device_view", "classcudf_1_1timestamp__scalar__device__view.html", null ],
      [ "type_to_name", "structcudf_1_1type__to__name.html", "structcudf_1_1type__to__name" ],
      [ "type_to_scalar_type_impl", "structcudf_1_1type__to__scalar__type__impl.html", "structcudf_1_1type__to__scalar__type__impl" ],
      [ "type_to_scalar_type_impl< cudf::dictionary32 >", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1dictionary32_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1dictionary32_01_4" ],
      [ "type_to_scalar_type_impl< cudf::list_view >", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1list__view_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1list__view_01_4" ],
      [ "type_to_scalar_type_impl< cudf::string_view >", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1string__view_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1string__view_01_4" ],
      [ "type_to_scalar_type_impl< cudf::struct_view >", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1struct__view_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01cudf_1_1struct__view_01_4" ],
      [ "type_to_scalar_type_impl< numeric::decimal128 >", "structcudf_1_1type__to__scalar__type__impl_3_01numeric_1_1decimal128_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01numeric_1_1decimal128_01_4" ],
      [ "type_to_scalar_type_impl< numeric::decimal32 >", "structcudf_1_1type__to__scalar__type__impl_3_01numeric_1_1decimal32_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01numeric_1_1decimal32_01_4" ],
      [ "type_to_scalar_type_impl< numeric::decimal64 >", "structcudf_1_1type__to__scalar__type__impl_3_01numeric_1_1decimal64_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01numeric_1_1decimal64_01_4" ],
      [ "type_to_scalar_type_impl< std::string >", "structcudf_1_1type__to__scalar__type__impl_3_01std_1_1string_01_4.html", "structcudf_1_1type__to__scalar__type__impl_3_01std_1_1string_01_4" ],
      [ "window_bounds", "structcudf_1_1window__bounds.html", "structcudf_1_1window__bounds" ]
    ] ],
    [ "numeric", "namespacenumeric.html", [
      [ "fixed_point", "classnumeric_1_1fixed__point.html", "classnumeric_1_1fixed__point" ],
      [ "scaled_integer", "structnumeric_1_1scaled__integer.html", "structnumeric_1_1scaled__integer" ]
    ] ],
    [ "nvtx3", "namespacenvtx3.html", [
      [ "argb", "structnvtx3_1_1argb.html", "structnvtx3_1_1argb" ],
      [ "category", "classnvtx3_1_1category.html", "classnvtx3_1_1category" ],
      [ "color", "classnvtx3_1_1color.html", "classnvtx3_1_1color" ],
      [ "domain", "classnvtx3_1_1domain.html", "classnvtx3_1_1domain" ],
      [ "domain_process_range", "classnvtx3_1_1domain__process__range.html", "classnvtx3_1_1domain__process__range" ],
      [ "domain_thread_range", "classnvtx3_1_1domain__thread__range.html", "classnvtx3_1_1domain__thread__range" ],
      [ "event_attributes", "classnvtx3_1_1event__attributes.html", "classnvtx3_1_1event__attributes" ],
      [ "message", "classnvtx3_1_1message.html", "classnvtx3_1_1message" ],
      [ "named_category", "classnvtx3_1_1named__category.html", "classnvtx3_1_1named__category" ],
      [ "payload", "classnvtx3_1_1payload.html", "classnvtx3_1_1payload" ],
      [ "registered_message", "classnvtx3_1_1registered__message.html", "classnvtx3_1_1registered__message" ],
      [ "rgb", "structnvtx3_1_1rgb.html", "structnvtx3_1_1rgb" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< cudf::data_type >", "structstd_1_1hash_3_01cudf_1_1data__type_01_4.html", "structstd_1_1hash_3_01cudf_1_1data__type_01_4" ]
    ] ],
    [ "default_allocator", "classdefault__allocator.html", null ],
    [ "int_fastdiv", "classint__fastdiv.html", "classint__fastdiv" ]
];